# Site settings
title: "On Software and Saving Faith"
author: "Aaron Yoo"
description: "This blog is a notepad for my ideas and an incubator for my thoughts. Topics generally center on software and philosophy. The ideas found here are often half-baked and in no way represent the interests of my employer or any organization I am affiliated with."
biography: "I am a software engineer and an ambassador for Christ. I think both of these things are well reflected in the content of my blog."
colophon: "©2020 Aaron Yoo. Theme by Hugo Sereno Ferreira"

baseurl: ""
url: "aarontyoo.com"

markdown: kramdown
highlighter: rouge
permalink: /blog/:year-:month-:day-:title/
