# Site settings
title: "Aaron Yoo"
author: "Aaron Yoo"
colophon: "©2020 Aaron Yoo. Theme by Hugo Sereno Ferreira"

baseurl: ""
url: "aarontyoo.com"

markdown: kramdown
highlighter: rouge
permalink: /blog/:year-:month-:day-:title/

gems: [jekyll-mermaid]

mermaid:
  src: 'assets/mermaid.min.js'